### ISSUE TITLE
Not working on RPI zero

### ISSUE THREAD

**Issue by lolecki** [maxvfischer/sonos-streaming#1]
![PXL_20231114_175241553](https://github.com/maxvfischer/sonos-streaming/assets/150838675/98b595cf-94c8-4c91-945e-9666cf7154d1)

Doesn't work on RPI zero wh

Get the following, any idea if it's a limitation of the rpinzero?
Did you optimise the image for pi3 or 4?

**Comment by maxvfischer** [comment]
I'm running it on a RPi4 and I sadly don't have a RPI Zero to debug it on.

When searching around (and also looking at your errors above), the problem seems to be connected to running docker/containerd on the RPi Zero. 

It seems like other people also have issues getting docker to run on RPi Zero:
* https://raspberrypi.stackexchange.com/questions/118612/running-docker-on-raspberry-pi-zero-w
* https://raspberrypi.stackexchange.com/questions/133527/installing-docker-on-a-pi-zero-w-or-a-pi-zero2

Instead of installing the pre-built `sonos-streaming` image, can you try to install the default RPi image from the `Raspberry Pi Imager`, and then install docker separately and see if this works?
